### ISSUE TITLE
How to customize closing animation of cookie bar

### ISSUE THREAD

**Issue by FrankMejzlik** [insites/cookieconsent#115]
Hello there,

first of all, I really like this script, it saved me lot of time, but I'm curious how to add also closing animation to cookie bar. I use bottom-dark and slideUp animation at the beginning is cool, but I'd be amazing to have slideDown  animation when user clicks "I agree" button.

Thanks very much for your tips.

**Comment by alexmorleyfinch** [comment]
In CookieConsent V2 this can be quite difficult, because the element is removed from the DOM on close. You may be able to add some CSS animations that run when an element is removed, but I'm not sure.

In CookieConsent V3 this would be much easier. You could add a CSS animation using the `onPopupClose` function.

**Comment by katerlouis** [comment]
I have to warm this up again:

Animating in with GSAP using `onPopupOpen` is nice.
But I don't see a way to animate the popup out with the given callback hooks.

How about a "beforePopupClose" or maybe removing of the DOM element after a promise is resolved?
