### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by JonnyBGod** [insites/cookieconsent#124]
Please publish this library to npm for easy installation.

**Comment by artursopelnik** [comment]
+1

**Comment by patroqueeet** [comment]
+1

**Comment by jmike** [comment]
Hey guys,

Since this issue has been open for 5 months with no action taken, I went ahead and published cookieconsent2 to the npm registry. The code is based on https://github.com/visionmobile/cookieconsent2.

Let me know if you want to assume ownership and I will gladly make the necessary changes.

Cheers,

**Comment by jmike** [comment]
I 've created a related pull request as well... https://github.com/silktide/cookieconsent2/pull/144

**Comment by alexmorleyfinch** [comment]
The project has undergone a significant rewrite, so we won't submit cookieconsent2 as an NPM module.

You may be happy to learn that CookieConsent V3 exists, and has been submitted as an NPM module

`npm install cookieconsent`

This new version includes significant improvements suggested by the community
