### ISSUE TITLE
Dismiss "Cookie consent" during site loading - stopped loading process

### ISSUE THREAD

**Issue by VatslauX** [insites/cookieconsent#145]
Please advise source the problem:
All browsers./ any OS
But Not reproduced on localhost - web issue only

Steps 
1. Load page with bootstrap buttons
2. Before content loaded fully - click dismiss button
E.R. all elements loaded, Cookie consent not displayed
A.R site loading stopped,  Cookie consent not displayed

![9911](https://cloud.githubusercontent.com/assets/17797084/17513578/77194224-5e36-11e6-8e0b-7edaaeeee166.png)

**Comment by alexmorleyfinch** [comment]
This is a bug due to clicking the "dismiss" button before tool is fully initialised. When the `dismiss` function is run, the `element` is removed from the DOM. I'm not sure why the whole website then falls over though.

The tool must remove the `element` and then throw an uncaught exception somewhere, possibly due to the `element` being prematurely removed. The tool is not programmed to handle premature input like this, but it should have been.

CookieConsent V2 is now deprecated. We recommend using CookieConsent V3, which does not have this issue, as the `element` is not removed from the DOM unless `destroy` is called.
