### ISSUE TITLE
CSS customization

### ISSUE THREAD

**Issue by ninonbane** [insites/cookieconsent#161]
Hi,
I would like to change the colors of the cookie banner.
I installed the code of this link [http://assets.cookieconsent.silktide.com/current/style.min.css] on my style.css file and changed it to the colors that I want to use but it doesn't change anything.
Maybe I'm missing one step ?
Can you please advice?

Thank you for your support.
Regards

**Comment by piiupilt** [comment]
Hello, 

This code belong to Cookie Consent v2, but we are currently on v3. 
Use the latest CSS and JS from the build folder in this repository and/or use our brand new [customiser](https://cookieconsent.insites.com/download/) to set custom colours.

**Comment by ninonbane** [comment]
Wow ! 
This is awesome!! This page is exactly what I was looking for!
I copied pasted the new code in my header.php instead of the last one but there is no cookie appearing anymore.
Is this normal ?

**Comment by piiupilt** [comment]
What do you mean by cookie - the cookie logo (which we have removed on version v3) or the whole popup? 

If the popup doesn't appear, it may mean, that you have already dismissed it once and it remembered your choice. Try using your site in incognito mode. 

If it still doen't appear there may be a javascript error (check the console). Moving the two scripts to the footer, just before the closing the body tag could help.

**Comment by ninonbane** [comment]
Hi,

Well I managed to do it but the 2 layout appear on my website : when I 
accept the 1st layout, there is the 2nd layout below as you can see on 
that picture.
How comes? Can you please advice ?

And will the user have to click on this pop up at every visit or does it 
last forever?
Thanks for your support.
Regards.





Logo <http://iconink.fr> 	
contact@iconink.fr <mailto:contact@iconink.fr>
www.iconink.fr <http://iconink.fr/> 	

Facebook <https://www.facebook.com/iconinkdesign.fr?ref=hl> 	Twitter 
<https://twitter.com/iconinkdesign> 	Instagram 
<https://www.instagram.com/iconink.design/>

  09 70 40 80 10

**Comment by alexmorleyfinch** [comment]
I am afraid there was no image attached to your latest response, or at least I was unable to find it.

User's will only have to dismiss the popup once, and their PC will remember their choice for 1 year (by default). You can extend the time by setting the `cookie.expiryDays` equal to a value of your choice. Set it to `1000` and the user's choice is preserved for 1000 days (unless they clear their cookies). You can use `-1` to never expire.

```
<script>
  window.cookieconsent.initialise({
    // ... your options ...
    cookie: {expiryDays: -1},
  });
</script>
```

**Comment by ninonbane** [comment]
Hi Alex,

It was just below my email.
Here attached it is.

That's great if it lasts for 1 year.
There is just this double box issue that I need to fix and I'm all good !

Can you please advice ?
Thanks




Logo <http://iconink.fr> 	
contact@iconink.fr <mailto:contact@iconink.fr>
www.iconink.fr <http://iconink.fr/> 	

Facebook <https://www.facebook.com/iconinkdesign.fr?ref=hl> 	Twitter 
<https://twitter.com/iconinkdesign> 	Instagram 
<https://www.instagram.com/iconink.design/>

  09 70 40 80 10

**Comment by alexmorleyfinch** [comment]
I think because the email is being sent through Github, the attached image is being removed.

Here is what I can see in my Gmail:

![screenshot from 2016-10-03 17-01-39](https://cloud.githubusercontent.com/assets/3381364/19044224/4378b0be-898b-11e6-83c6-6fe1050f5505.png)

If you want, It is possible to attach images via Github by dragging and dropping the image onto the text area

**Comment by ninonbane** [comment]
Sure. I didn't think about it before.
Here it is
Thanks
<img width="1275" alt="capture d ecran 2016-10-03 a 09 47 42" src="https://cloud.githubusercontent.com/assets/22530345/19050903/3fd989ca-8976-11e6-92f9-e04e10d82aaa.png">

**Comment by alexmorleyfinch** [comment]
It's hard to find out exactly what's going on without looking directly at the code, but I'll try.

The popup displayed in this image is CookieConsent V2, as only version 2 has an image of a cookie under the button. I'm not sure which version you want to run, so I'll describe both.

First of all, Is there any chance that you are running both V2 and V3 at the same time? You should ensure that you are only running one of these snippets of code.

-----------------------------------------------------------------

If you want to use Version 3, it should look something like this:

```
<!-- this works best in the head tag -->
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.1/cookieconsent.min.css" />

<!-- this works best at the end of the body tag -->
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.1/cookieconsent.min.js"></script>
<script>
  window.cookieconsent.initialise({
    "palette":{
      "popup":{"background":"#000"},
      "button":{"background":"#f1d600"},
    },
    "theme":"classic",
    "position":"bottom-right"
  });
</script>
```

In version 3, the layout is defined by `theme`. As of now, we only have the `classic` and `edgeless` options (but you can create your own). The colours can be set using `palette` (the palette options are defined at https://cookieconsent.insites.com/documentation/javascript-api/#palette_options).

Optionally, you can remove the `palette` option and copy the CSS file and change the colours (as you stated earlier). There are many more options for version 3 which can be found at https://cookieconsent.insites.com/documentation/javascript-api/

-----------------------------------------------------------------

If you want to use version 2, it should look something like this:

```
<script type="text/javascript">
  window.cookieconsent_options = {
    "message":"This website uses cookies to ensure you get the best experience on our website",
    "dismiss":"Got it!",
    "learnMore":"More info",
    "link":null,
    "theme":"dark-floating"
  };
</script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.10/cookieconsent.min.js"></script>
```

In version 2, the layout is defined directly by the `theme` option. In the example above, the theme is `dark-floating`. You can change `dark-floating` to a number of other options in order to change the layout. E.G. `light-floating`, `light-top`, `light bottom`, `dark-floating`, `dark-top` and `dark-bottom`.

Changing these options will alter the layout of the plugin.

I may have not been clear, so please don't hesitate to ask any more questions. Thank you.

**Comment by ninonbane** [comment]
Thank you so much Alex !

I had an old line on my footer.php.
That's why.

Thanks so much for your help.
Regards


Logo <http://iconink.fr> 	
contact@iconink.fr <mailto:contact@iconink.fr>
www.iconink.fr <http://iconink.fr/> 	

Facebook <https://www.facebook.com/iconinkdesign.fr?ref=hl> 	Twitter 
<https://twitter.com/iconinkdesign> 	Instagram 
<https://www.instagram.com/iconink.design/>

  09 70 40 80 10

**Comment by alexmorleyfinch** [comment]
Glad to hear you sorted it :+1:

**Comment by tre3141** [comment]
i am having issues with seeing the button on certain browser additions. i would like to update the size of the text within the widget? do you support this?
