### ISSUE TITLE
custom elements setup seems to be skipped on initialise

### ISSUE THREAD

**Issue by saelfaer** [insites/cookieconsent#169]
When defining a custom element for the message (we use fontAwesome to include an info icon in front of the text), It seems like the cookie concent script skips that, even though the docs tell us how it should be used.

```
    <script>
        // Cookie Consent code
        window.addEventListener("load", function() {
            window.cookieconsent.initialise({
                "elements": {
                    "message": '<span id="cookieconsent:desc" class="cc-message"><span class="fa fa-info"></span>{{message}}</span>'
                },
                "content": {
                    "message": "This site uses cookies blah blah.",
                    "dismiss": "OK",
                    "link": "read more",
                    "href": "https://www.mylink.com"
                }
            });
        });
    </script>
```

This outputs the default message in it's default element layout. Not sure what i'm doing wrong here?

**Comment by marcusadolfsen** [comment]
The same problem here. Trying to add a class to the "link" element.

**Comment by TheRealMaN** [comment]
does anyone solved the problem?

**Comment by DanielRuf** [comment]
See https://github.com/insites/cookieconsent/issues/228

**Comment by thexmanxyz** [comment]
@saelfaer @marcusadolfsen @TheRealMaN This a real issue it has already been solved be using the API correctly. If you modify `message` under `elements` you also have to change your `layout` or `layouts` attribute otherwise the wrong layout will be loaded which won't have a output for `message`.

If you want to change `message` you have to set `layout: 'basic-header`. see also #365

**Comment by saelfaer** [comment]
that does seem like an adequate solution.
