### ISSUE TITLE
Accessing consent status outside of plugin?

### ISSUE THREAD

**Issue by Sinmok** [insites/cookieconsent#172]
There doesn't appear to be any way to access the consented status from outside of the initialize() call.

If I need to check if cookies are consented elsewhere in my script, I can't.

How do you get the status from outside of the initialize() call?

window.cookieconsent.hasConsented() doesnt seem to work. What is the suggested way of dealing with this?

**Comment by piiupilt** [comment]
The variables can not be accessed outside the CC code to prevent conflicts with other code. 

However, you can use a callback hook in CC initialisation to set global variables or run scripts of your own. For example:

`onInitialise: function(status) { window.yourVariable = this.hasConsented(); }`

More information about callbacks can be found here: https://cookieconsent.insites.com/documentation/javascript-api/

**Comment by ParallelUniv3rse** [comment]
In case anyone is facing the same inconvenience - I've injected the cookieconsent window object with the getStatus function from the CookiePopup instance like so: 
`onInitialise: function (status) {
    window.cookieconsent.getStatus = this.getStatus.bind(this);
  },
  onPopupOpen: function () {
    window.cookieconsent.getStatus = this.getStatus.bind(this);
  }`
They are both needed since the first one fires only when there was a choice made and the second one fires when there was no consent yet.
