### ISSUE TITLE
freegeoip error

### ISSUE THREAD

**Issue by p4rnicke** [insites/cookieconsent#210]
cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js:1 
The service[0] (//freegeoip.net/json/?callback={callback}) responded with the following error Error: 
Error [UNKNOWN]: Invalid response (SyntaxError: Unexpected end of JSON input)

Using the suggested:
law: {
                    regionalLaw: false,
                },
                location: true,

**Comment by alexmorleyfinch** [comment]
To find the users location, the default setup of CookieConsent uses free location APIs ([FreeGeoIP](https://freegeoip.net/), [IPInfo](https://ipinfo.io/), [Maxmind](https://www.maxmind.com)).

That specific error occurs because the response from the endpoint `http://freegeoip.net/json/` (or `https`) responded with invalid JSON. It would be easier to know *why* the FreeGeoIP failed if you could provide the details for the request and response data.

When a request fails, CookieConsent will try the next free service. If all 3 services fail, then the Location module gives up trying and shows the popup anyway.

If this was the only error you got, its possible the first service failed, but the second service succeeded.

These free services can be unreliable (which is why we try 3 of them) so it is recommended that you hook up your own location detection method. You can find details for how to do that [here](https://cookieconsent.insites.com/documentation/location-services-cookie-law/).

**Comment by alexmorleyfinch** [comment]
I added another issue to lower to level from an error to a warning

https://github.com/insites/cookieconsent/issues/215
