### ISSUE TITLE
Conflict with font awesome 5

### ISSUE THREAD

**Issue by chunty** [insites/cookieconsent#252]
Can you help with this issue at all https://stackoverflow.com/questions/48113016/silktide-cookie-consent-3-0-3-conflict-with-font-awesome-5-0-2-using-css-pseudo

**Comment by alexmorleyfinch** [comment]
I could be massively wrong, this is just a guess.

I think this is happening because cookie consent defines the `aria-labelledby` attr as `cookieconsent:desc` but the `:` is the pseudo element selector, therefor it is trying to find a `:desc` pseudo selector (which clearly doesn't exist).

You MIGHT be able to stop this error by defining it in jQuery

```js
jQuery.extend(jQuery.expr[':'], {
  // add the :desc pseudo-selector to jQuery
  desc: function (el, index, selector) {
    // stub for now
    return false;
  }
});
```

or what ever selector library you may be using.

Thats my best guess at least
