### ISSUE TITLE
Clicking 'Got It!' button creates widget when location is set to true

### ISSUE THREAD

**Issue by tttmack123** [insites/cookieconsent#299]
If location is set to false and I click the 'Got It!' button, the banner completely disappears and there is no widget to show it again. 

However if location is set to true, when you click the 'Got It!' button, the banner is hidden but a widget is also created that shows the banner again when it is clicked. **How do we hide this widget when location is set to true?**

This can be reproduced on this URL (where the 'Cookie Policy' widget is in the bottom-left corner after clicking the 'Got It!' button): https://cookieconsent.insites.com/app/themes/insites-cookie-consent/examples/example-6-location.html

**Comment by alexmorleyfinch** [comment]
Sometimes you can't... The reason it is being shown is because the country you are in has specified that the banner MUST be `revokable`. So even if you set `revokable` to false (the default). It can get set to true automatically by the Location module.

There is a way to turn this off using the regional specific settings.

```js

  window.cookieconsent.initialise({
    // your options ...
    law: {
      regionalLaw: false,
    },
    location: true,
  });
```
