### ISSUE TITLE
[GDPR SUGGESTION] The best way implemented i have found

### ISSUE THREAD

**Issue by eurobank** [insites/cookieconsent#324]
This is in my opinion the BEST way to handle cookies. Genious. 

3 Options with information for the user to select. Can't be more clear than this. Those options are located in the "learn more" initial link.

Check hostgator . com to see it live.

![2](https://user-images.githubusercontent.com/4467158/40085074-fd81b06e-58a1-11e8-8e2a-a3b1cdc0e03e.png)

![3](https://user-images.githubusercontent.com/4467158/40085077-008d7c48-58a2-11e8-9ad5-55ca5f6e747d.png)

![1](https://user-images.githubusercontent.com/4467158/40085071-fa2f5c22-58a1-11e8-8d65-e6ef3db72b3b.png)

**Comment by Braintelligence** [comment]
This isn't enough for the 2019 upcoming EU ePrivacy regulation which explicitly asks for prior atomic consent of each and every cookie that is not 100% technically needed (for example you don't need consent for the shopping cart cookie of an e-commerce site, because it's technically needed).

**Comment by eurobank** [comment]
@Braintelligence I have no idea what 2019 EU thing is, i'm talking about GDPR of 2016 that will be forced in a week or so. 

For GDPR the above example is more than enough and i guess EIG group (that has a few hundred of hosting companies by now) knows what to do and what not to do.

**Comment by Braintelligence** [comment]
All I'm saying is that it's moot to apply changes for something that is due very soon, if you just could apply changes that satisfy the needs of GDPR and ePrivacy alike. 

Sure the EIG group won't comply to ePrivacy just yet, because it's hugely restrictive and impacts their commercial agenda on their website. But they also use their own cookie consent scripts. I don't see any reason why this repo should follow their example, just to throw everything over the board when ePrivacy hits next year.

If the owners of this repo want to create a GDPR- and then also an ePrivacy-version of this script (which would fulfill GDPR-needs anyway), then it's alright but unnecessary and redundant work.

**Comment by eurobank** [comment]
@Braintelligence I'm not saying to adopt anything (or not) for the script. But the whole design and idea is perfect, simple and explains anything. I still find it brilliant.

Me as a user, seeing that, it was extremely clear what to accept and what not. Simple as that.

**Comment by Braintelligence** [comment]
I didn't comment on the design, I commented on the value of the development of such a design for this repo. 

IMO it would be more elegant to develop in compliance of the ePrivacy regulation, because that's where we're headed right now. 

Concerning cookie consent for GDPR you don't even need above design. The most important change is that you need to state what the cookies you use are meant for and how they are necessary for you to provide the experience of your website in the data privacy segment of your website. (As written in Art. 6 Abs. 1 S. 1 lit. f GDPR/DSGVO)

If you think implementing above design on your website is enough to comply with GDPR you're wrong. Actually IMO it doesn't satisfy anything GDPR-relevant at all, other than allowing your visitors to allow cookies that you can't explain the necessity/legitimate interest of (again Art. 6 Abs. 1 S. 1 lit. f GDPR/DSGVO) and thus have to make them optional.

**Comment by ayumihamsaki** [comment]
@eurobank @Braintelligence Interesting read of both your comments, Can I add a comment here and say, that cookie consent from Hostgator is made by trustarc. I was actually looking at it yesterday. It would not pass GDPR and ePrivacy and you should avoid that.

I give you a reason, why:

Let's say I have a website and it has Google Analytics, that would be under Tracking Cookies, which that plugin doesn't even cover, but let's just say I put it under Advertising Cookies.

To make the plugin pass GDPR and ePrivacy the user would need to be able to turn off Google Analytics **ONLY** and not a range of cookies!

That is the reason why that plugin in my mind doesn't pass the new laws.

**Comment by Braintelligence** [comment]
@diegoreunion Again, I don't understand what you guys mean by "GA cookie". If I visit a website with Google Analytics enabled, I don't necessarily get any Google Analytics cookie. What would GA need a cookie for? All the info they want come from calling the GA script itself. A session for this is not needed in all cases.

Though for GDPR you need to create GA opt-out methods on your website, if we're talking about this.

**Comment by diegoreunion** [comment]
Yes, You are right. The Script runs on the site but from what I understand it also implements cookies in order to track whats happening. I see them on my site with the names ga_ gid_ and so on.
https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage

**Comment by Braintelligence** [comment]
I see, then you really need to mention this; just like the opt-out-cookie.

**Comment by zissop** [comment]
Technically and strictly gdpr speaking all these implementations lack what data are gathered and what process it is made on them. They just want to fool visitors and law.

**Comment by Braintelligence** [comment]
@zissop That's what the data privacy statement is for. This is not the job of a cookie consent banner.

**Comment by NathanCH** [comment]
Has everyone here moved away from cookieconsent as it is not GDPR compliant? If so, what tool are you using?

**Comment by digibum** [comment]
Haven't found any other valid solution. We will probably develop our own solution specific for EU residents.

**Comment by diegoreunion** [comment]
I am testing the GDPR Plugin for WP that is very promising
https://wordpress.org/plugins/gdpr/

**Comment by alexmorleyfinch** [comment]
Thanks for great suggestions! We'll take all of this into consideration when implementing our own GDPR plugin 😄 Thanks! Closing this issue now

**Comment by TheMangoTrain** [comment]
"2019 upcoming EU ePrivacy regulation" whoa whoa whoa... you mean there's MORE changes coming?

**Comment by Braintelligence** [comment]
> "2019 upcoming EU ePrivacy regulation" whoa whoa whoa... you mean there's MORE changes coming?

Indeed, though it seems they are postponed to 2020. It gets easier to track websites via tools like Matomo, to mention a positive change; but cookie consent has to happen in a more atomic way, if I remember correctly.
