### ISSUE TITLE
Plugin blocks captcha on "Contact Form to Email" plugin

### ISSUE THREAD

**Issue by jon-tibbetts** [insites/cookieconsent#370]
If the "Cookie Consent" plugin is activated, it seems to not allow captcha to work with the "Contact Form to Email" plugin. If the "Cookie Consent" plugin is de-activated everything seems to work fine.

**Comment by Dolondro** [comment]
Incompatibility between third party plugins in wordpress is kind of a problem of the ecosystem.

The maintainer for the wordpress plugin no longer works for us and to be honest it's very unlikely anyone would end up looking at this.

I would recommend moving to use the cookieconsent javascript directly instead of the wordpress plugin. I can't guarantee it'll work in conjunction with the "Contact From to Email" plugin, but I suspect it'd solve your issue.
