### ISSUE TITLE
GDPR "retain consent" issue

### ISSUE THREAD

**Issue by stapeleliz** [insites/cookieconsent#371]
Is there some way, with this script, to "retain consent" (if given) for cookies for a particular user? Especially when the user hasn't (and won't be) signing up for anything, logging in to anything, or in any other manner telling the website who s/he is?

Thank you!

**Comment by neijek** [comment]
> Proof of consent vs Records of consent:
> The Cookie Law does not require that records of consent be kept but instead indicates that you should be able to prove that consent occurred (even if that consent has been withdrawn). The simple way to do this would be to use a cookie solution that employs a prior blocking mechanism as under such circumstances, cookie installing scripts will only be run after consent is attained. In this way, the very fact that scripts were run may be used as sufficient proof of consent.
> To further illustrate this point, imagine that the ability to run cookies is a room, the cookie solution is the door and the consent is the act of rotating the door handle; you can only enter through the door into the room if the door handle is rotated (the act of giving consent). In this example, if you’ve entered the room it can only be because the door handle was rotated and, therefore, your presence in the room is sufficient proof of this fact.
> 
> While actually keeping track of the consent acquired is not specifically mentioned by the Directive, some Member State guidelines may require it. Italy, for example, requires that.
> 
> the publisher must in any case keep track of the user’s consent. To that end, an ad-hoc technical cookie might be relied upon . . . The availability of this type of “documentation” of the user’s preferences will enable the publisher not to display the information notice on subsequent visits made by that user to the website.
> 
> This means that making use of a technical cookie in such a way (as quoted) is sufficient and may be relied upon to meet the State’s requirement of “keeping track” of the consent acquired. The Authority prescribes a maximum validity (the ability to “remember” or “keep track” of the consent) of 12 months from the last site visit. The iubenda Cookie Solution makes use of this method of “consent tracking”.


this might help, so in theory using the explicit contect (op in) with a 356 day experation and block of cookies till op in is given will clear the requirement.

**Comment by alexmorleyfinch** [comment]
I'm not sure if I understand your question correctly, but from what I understand, yes! This functionality should exist out-of-the-box. When the user clicks "accept" or "deny", then we remember what that user chose so when they come back again they shouldn't be pestered with the banner! We don't need the user to log in or anything. We remember the users choice using cookies (which are stored on their computer)

**Comment by alexmorleyfinch** [comment]
It should be noted that CookieConsent is NOT GDPR compliant. It was designed to work with the "ePrivacy Directive" which has been superseded by GDPR. Therefore using CookieConsent for may not give you any protection. We don't plan on fixing this for CookieConsent because we are working on a new plugin especially for GDPR.

There is no real way to "retain consent" correctly anyway, because cookies are tied to a machine, not a person. Therefor you can only prove that the machine has consented, never the person sat at the machine. In that aspect, mobile phones would need to implement faciaI recognition in order to "retain consent", something which they clearly don't do.

I am NOT a GDPR expert, but I think setting a cookie on a persons machine for non-logged in users which remembers consent is fine. (Again, I am NOT a GDPR expert).
