### ISSUE TITLE
cookieconsent.min.js error

### ISSUE THREAD

**Issue by 2amredart** [insites/cookieconsent#415]
When I looked at the Chrome console, I get this error as per attached image.
Is this error normal for cookieconsent.min.js?

![cookieconsent min js_issue_](https://user-images.githubusercontent.com/12223600/42866933-9c27f482-8aa0-11e8-9d5f-ce849caad572.png)

**Comment by alexmorleyfinch** [comment]
This is happening because the location service is failing. There are 3 default location services and the first one is no longer working because they deprecated their API. This should have been fixed in the latest version. So you can try using the [latest version](https://github.com/insites/cookieconsent/releases)

Otherwise you can disable the first location service by modifying the configuration:

```js
cookieconsent.initialise({
  // ... your options ...

  location: {
    services: ['ipinfo', 'maxmind']
  }
})
```

(it was `['freegeoip', 'ipinfo', 'maxmind']` by default in the last version)
