### ISSUE TITLE
"Cookie policy"-tab not removable

### ISSUE THREAD

**Issue by Kwarks85** [insites/cookieconsent#430]
Hey there,

first I want to say thanks for that great solution. We use it in different contexts. A client of ours wanted to get rid of the "Cookie policy"-tab that shows (especially on mobile) after you have accepted the terms so that you can review the terms. Client is based in Germany.

I tried several options including manipulating the autoAttach or misusing the law settings to simulate users not being in Germany. As far as I understood in Germany it is automatically set to appear after accepting or declining the cookies. How would I need to change the code in order to still have the initial consent window, but after accepting or declining there is no more tab?

![image](https://user-images.githubusercontent.com/7770286/43465687-25ffad02-94de-11e8-857c-a763ea837596.png)

**Comment by inveress** [comment]
I used a bit of CSS to hide it:

```
.cc-revoke {
  display: none !important;
}
```

**Comment by driespieters** [comment]
Would be nice to have this as a configuration option. 

Personally I would turn it off by default, as most sites will already have a link to the cookie policy in the footer.

**Comment by uturnr** [comment]
I hide mine by using the following line in the configuration option.

`revokeBtn: '<div style="display: none;"></div>',`

However I provide a method to change the setting in my cookie policy.

**Comment by Kwarks85** [comment]
Thanks a lot! Got it working

**Comment by commwork** [comment]
> However I provide a method to change the setting in my cookie policy.

How do you do that?

**Comment by uturnr** [comment]
@commwork 
```
window.cookieconsent.initialise({
     // options go here
  }, function (popup) {
    window.cookiePopup = popup;
  });
```

Then my button in the cookie policy calls `window.cookiePopup.open()` on click. (This doesn't modify the user's selection unless they then click Allow or Decline)

**Comment by TheMangoTrain** [comment]
+1 to turning this off by default. Once the user has interacted, you want them to forget about it.

Footers contain a variety of legal links already. This is the natural default place to put such links like "Privacy Policy", "Cookie Policy", "Cookie Settings", "Terms of Services", etc.

Why would cookies deserve it's own sticky button, and not the other variety of legal links?

In any case, such a fixed button actually should be labeled "Cookie Settings" because that's what it links to... a prompt to control your cookie settings. Whereas "Cookie Policy" is usually a dedicated page with many paragraphs of text.

**Comment by TheMangoTrain** [comment]
Also, it's strange this button would have the class "cc-revoke", since this is simply a shortcut to change cookie settings (revoke or not). Another case of code language being confusing.
